# Generated by Django 4.0.5 on 2022-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='telephone',
            field=models.IntegerField(max_length=11),
        ),
    ]
