# Generated by Django 4.0.5 on 2022-06-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_client_telephone_alter_manufacturer_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
