# Generated by Django 4.0.5 on 2022-06-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_client_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='signed_at',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='created_at',
            new_name='signed_at',
        ),
    ]
